import express from 'express';
import { getAvailableTemplates } from '../templates/templates.js';
import { generateSpecificFrog, generateRandomFrog } from '../services/frog-generator.js';

const router = express.Router();
/**
 * POST /api/generate-frog
 * Generate AI-powered ASCII frog
 */
router.post('/generate-frog', (req, res) => {
    try {
        const { frog = 'classic' } = req.body;

        console.log(`🐸 AI generating frog - Type: ${frog}`.cyan);

        const frogData = generateSpecificFrog(frog);

        res.json({
            success: true,
            ...frogData
        });

    } catch (error) {
        console.error('Error generating AI frog:', error.message);
        res.status(400).json({
            success: false,
            error: error.message
        });
    }
});

/**
 * GET /api/frogs
 * Get all available AI-generated frogs
 */
router.get('/frogs', (req, res) => {
    try {
        const frogs = getAvailableTemplates().map(template => ({
            id: template.id,
            name: template.name,
            preview: template.preview,
            type: 'AI-generated'
        }));
        res.json({
            success: true,
            frogs,
            totalFrogs: frogs.length
        });
    } catch (error) {
        console.error('Error fetching frogs:', error.message);
        res.status(500).json({
            success: false,
            error: 'Failed to fetch frogs'
        });
    }
});



/**
 * GET /api/random-frog
 * Generate a random AI-powered frog
 */
router.get('/random-frog', (req, res) => {
    try {
        const frogData = generateRandomFrog();

        res.json({
            success: true,
            ...frogData
        });

    } catch (error) {
        console.error('Error generating random AI frog:', error.message);
        res.status(500).json({
            success: false,
            error: 'Failed to generate random frog'
        });
    }
});

/**
 * GET /api/terminal-config
 * Get terminal theme, configuration, and messages
 */
router.get('/terminal-config', (req, res) => {
    try {
        const config = {
            theme: {
                background: '#0d1117',
                foreground: '#e6edf3',
                cursor: '#58a6ff',
                black: '#484f58',
                red: '#ff7b72',
                green: '#3fb950',
                yellow: '#d29922',
                blue: '#58a6ff',
                magenta: '#bc8cff',
                cyan: '#39c5cf',
                white: '#b1bac4',
                brightBlack: '#6e7681',
                brightRed: '#ffa198',
                brightGreen: '#56d364',
                brightYellow: '#e3b341',
                brightBlue: '#79c0ff',
                brightMagenta: '#d2a8ff',
                brightCyan: '#56d4dd',
                brightWhite: '#f0f6fc'
            },
            settings: {
                fontFamily: 'Fira Code, monospace',
                fontSize: 14,
                rows: 24,
                cols: 80,
                cursorBlink: true,
                scrollback: 0,
                disableStdin: true
            },
            messages: {
                welcome: '🤖🐸 Welcome to AI Frog Generator Terminal!',
                prompt: 'ai-frog@terminal:~$ '
            }
        };

        res.json({
            success: true,
            config
        });
    } catch (error) {
        console.error('Error fetching terminal config:', error.message);
        res.status(500).json({
            success: false,
            error: 'Failed to fetch terminal configuration'
        });
    }
});

/**
 * POST /api/format-clipboard
 * Format AI-generated ASCII art and species name for clipboard copying
 */
router.post('/format-clipboard', (req, res) => {
    try {
        const { ascii, frogName } = req.body;

        if (!ascii || !frogName) {
            return res.status(400).json({
                success: false,
                error: 'ASCII art and frog name are required'
            });
        }

        // Remove ANSI color codes for plain text copy
        const plainAscii = ascii.replace(/\x1b\[[0-9;]*m/g, '');

        // Remove ANSI color codes from frog name for plain text copy
        const plainFrogName = frogName.replace(/\x1b\[[0-9;]*m/g, '');

        // Combine ASCII art with frog name
        const fullText = `${plainAscii}\n\n${plainFrogName}\n\nGenerated by AI`;

        res.json({
            success: true,
            formattedText: fullText
        });

    } catch (error) {
        console.error('Error formatting clipboard text:', error.message);
        res.status(500).json({
            success: false,
            error: 'Failed to format clipboard text'
        });
    }
});

export default router;
